import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";

const fadeInUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } }
};

export default function BioHarmonyAnalytics() {
  return (
    <div className="flex flex-col min-h-screen pt-20">
      <section className="py-20 bg-card border-b border-border">
        <div className="container px-4 md:px-6 max-w-4xl mx-auto text-center">
          <motion.div initial="hidden" animate="visible" variants={fadeInUp} className="space-y-6">
            <h1 className="text-4xl md:text-6xl font-serif text-primary">BioHarmony Analytics</h1>
            <p className="text-xl text-muted-foreground font-light leading-relaxed">
              Proprietary wellness reporting that turns complex energetic data into clear, actionable insights.
            </p>
          </motion.div>
        </div>
      </section>

      <section className="py-24 bg-background">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto space-y-12">
            <div>
              <h2 className="text-3xl font-serif text-primary mb-6">What is BioHarmony Analytics?</h2>
              <p className="text-lg text-muted-foreground leading-relaxed mb-4">
                The technology behind frequency wellness is incredibly sophisticated, often producing data that can be overwhelming to read. BioHarmony Analytics is our proprietary interpretation layer designed to solve this problem.
              </p>
              <p className="text-lg text-muted-foreground leading-relaxed">
                We translate the raw, detailed energetic patterns generated by the AO Scan into beautifully formatted, easy-to-read wellness reports. We remove the confusing charts and replace them with clear, client-friendly language.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 my-16">
              <div className="bg-card p-8 rounded-2xl border border-border shadow-sm">
                <div className="w-12 h-12 rounded-full bg-secondary/20 flex items-center justify-center mb-6">
                  <div className="w-4 h-4 rounded-full bg-secondary"></div>
                </div>
                <h3 className="font-serif text-xl text-primary mb-3">Clarity over Complexity</h3>
                <p className="text-muted-foreground">
                  Our reports prioritize understanding. You will see exactly where your energetic patterns are balanced and where they may need support.
                </p>
              </div>
              <div className="bg-card p-8 rounded-2xl border border-border shadow-sm">
                <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mb-6">
                  <div className="w-4 h-4 rounded-full bg-primary"></div>
                </div>
                <h3 className="font-serif text-xl text-primary mb-3">Actionable Insights</h3>
                <p className="text-muted-foreground">
                  Beyond just showing data, the analytics provide clear context so you can make informed wellness choices in your daily life.
                </p>
              </div>
            </div>

            <div>
              <h2 className="text-3xl font-serif text-primary mb-6">Why It Matters</h2>
              <p className="text-lg text-muted-foreground leading-relaxed mb-4">
                We believe that understanding your body shouldn't require a degree in energetic medicine. When you understand your wellness insights clearly, you are empowered to support your body's natural state of balance.
              </p>
              <p className="text-lg text-muted-foreground leading-relaxed">
                Every AO Scan session includes these proprietary reports, and our Practitioner Review sessions provide dedicated time to walk through them with Kathy directly.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-primary text-primary-foreground text-center">
        <div className="container px-4 md:px-6">
          <h2 className="text-3xl md:text-4xl font-serif mb-8">Gain Clarity on Your Wellness</h2>
          <Button asChild size="lg" className="rounded-full bg-background text-foreground hover:bg-background/90 px-10 h-14 text-lg" data-testid="analytics-book-cta">
            <Link href="/contact">Book a Session</Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
