import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";

const fadeInUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } }
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.15 } }
};

export default function BioHarmonyAnalytics() {
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-[#060D0D] to-[#091515]">

      <section className="py-24 border-b border-white/8">
        <div className="container px-4 md:px-6 max-w-4xl mx-auto text-center">
          <motion.div initial="hidden" animate="visible" variants={fadeInUp} className="space-y-6">
            <p className="text-[#BFA14A] text-xs uppercase tracking-[0.2em] font-sans">by BioHarmony Solutions</p>
            <h1 className="text-4xl md:text-6xl font-serif text-[#F4EFE6]">BioAnalytics</h1>
            <p className="text-xl text-[#F4EFE6]/60 font-light leading-relaxed max-w-2xl mx-auto">
              Complex Scan Data. Clear Human Insight.
            </p>
            <p className="text-base text-[#F4EFE6]/40 font-light leading-relaxed max-w-xl mx-auto">
              Personalized, easy-to-understand wellness reports for clients and practitioners.
            </p>
          </motion.div>
        </div>
      </section>

      <section className="py-24">
        <div className="container px-4 md:px-6">
          <div className="max-w-3xl mx-auto space-y-16">

            <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeInUp} className="space-y-5">
              <h2 className="text-3xl font-serif text-[#F4EFE6]">What is BioAnalytics?</h2>
              <p className="text-lg text-[#F4EFE6]/60 leading-relaxed">
                The technology behind frequency wellness is incredibly sophisticated, often producing data that can be overwhelming to read. BioAnalytics is our proprietary interpretation layer — by BioHarmony Solutions — designed to solve this problem.
              </p>
              <p className="text-lg text-[#F4EFE6]/60 leading-relaxed">
                We translate the raw, detailed energetic patterns generated by the AO Scan into beautifully formatted, easy-to-read wellness reports. We remove the confusing charts and replace them with clear, client-friendly language.
              </p>
            </motion.div>

            <motion.div
              initial="hidden" whileInView="visible" viewport={{ once: true }} variants={staggerContainer}
              className="grid grid-cols-1 md:grid-cols-2 gap-6"
            >
              {[
                {
                  dot: "bg-[#BFA14A]",
                  title: "Clarity over Complexity",
                  desc: "Our reports prioritize understanding. You will see exactly where your energetic patterns are balanced and where they may need support."
                },
                {
                  dot: "bg-[#1F8888]",
                  title: "Actionable Insights",
                  desc: "Beyond just showing data, the analytics provide clear context so you can make informed wellness choices in your daily life."
                }
              ].map((card, i) => (
                <motion.div
                  key={i}
                  variants={fadeInUp}
                  whileHover={{ scale: 1.02 }}
                  className="bg-white/5 backdrop-blur-md border border-white/10 p-8 rounded-2xl hover:border-[#BFA14A]/25 hover:shadow-[0_0_30px_rgba(191,161,74,0.08)] transition-all duration-300"
                >
                  <div className="w-10 h-10 rounded-full bg-white/8 flex items-center justify-center mb-6">
                    <div className={`w-3 h-3 rounded-full ${card.dot}`}></div>
                  </div>
                  <h3 className="font-serif text-xl text-[#BFA14A] mb-3">{card.title}</h3>
                  <p className="text-[#F4EFE6]/55 text-sm leading-relaxed">{card.desc}</p>
                </motion.div>
              ))}
            </motion.div>

            <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeInUp} className="space-y-5">
              <h2 className="text-3xl font-serif text-[#F4EFE6]">Why It Matters</h2>
              <p className="text-lg text-[#F4EFE6]/60 leading-relaxed">
                We believe that understanding your body shouldn't require a degree in energetic medicine. When you understand your wellness insights clearly, you are empowered to support your body's natural state of balance.
              </p>
              <p className="text-lg text-[#F4EFE6]/60 leading-relaxed">
                Every AO Scan session includes these proprietary reports, and our Practitioner Review sessions provide dedicated time to walk through them with Kathy directly.
              </p>
            </motion.div>

          </div>
        </div>
      </section>

      <section className="py-24 border-t border-white/8 text-center bg-gradient-to-b from-transparent to-[#040A0A]">
        <div className="container px-4 md:px-6">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeInUp} className="space-y-6">
            <h2 className="text-3xl md:text-4xl font-serif text-[#F4EFE6]">Gain Clarity on Your Wellness</h2>
            <Button
              asChild
              size="lg"
              className="rounded-full bg-[#0F5C5E] text-[#F4EFE6] border border-[#BFA14A]/20 px-10 h-14 text-base shadow-[0_0_20px_rgba(191,161,74,0.25)] hover:shadow-[0_0_35px_rgba(191,161,74,0.45)] transition-all duration-300"
              data-testid="analytics-book-cta"
            >
              <Link href="/contact">Book a Session</Link>
            </Button>
          </motion.div>
        </div>
      </section>

    </div>
  );
}
