import { pgTable, serial, varchar, boolean, text, timestamp, integer } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const scanRequestsTable = pgTable("scan_requests", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 50 }),
  reportType: varchar("report_type", { length: 50 }).notNull(),
  language: varchar("language", { length: 10 }).notNull().default("en"),
  fileName: varchar("file_name", { length: 255 }),
  whatsapp: boolean("whatsapp").default(false),
  plan: varchar("plan", { length: 20 }),
  paymentStatus: varchar("payment_status", { length: 20 }).notNull().default("pending"),
  pipelineStage: varchar("pipeline_stage", { length: 30 }).notNull().default("queued"),
  stageEnteredAt: timestamp("stage_entered_at"),
  pipelinePaused: boolean("pipeline_paused").notNull().default(false),
  pipelineError: varchar("pipeline_error", { length: 500 }),
  deliveredEmailSentAt: timestamp("delivered_email_sent_at"),
  paymentReminderSentAt: timestamp("payment_reminder_sent_at"),
  bioharmonyScore: integer("bioharmony_score"),
  scoreBreakdown: text("score_breakdown"),
  note: text("note"),
  adminNote: text("admin_note"),
  starred: boolean("starred").notNull().default(false),
  flagged: boolean("flagged").notNull().default(false),
  referralSource: varchar("referral_source", { length: 100 }),
  referrerEmail: varchar("referrer_email", { length: 255 }),
  promoCode: varchar("promo_code", { length: 50 }),
  discountAmount: integer("discount_amount"),
  tags: text("tags").array().default(sql`'{}'`),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
